(define eceval-operations
  (list 
        ; inbuilt scheme operators
        (list 'read read)
        
        ; operators from scheme-operators.scm
        (list 'self-evaluating? self-evaluating?)
        (list 'variable? variable?)
        (list 'quoted? quoted?)
        (list 'text-of-quotation text-of-quotation)
        (list 'assignment? assignment?)
        (list 'assignment-variable assignment-variable)
        (list 'assignment-value assignment-value)
        (list 'definition? definition?)
        (list 'definition-variable definition-variable)
        (list 'definition-value definition-value)
        
        CONTINUE HERE
        (list 'if? if?)
        (list 'announce-output display)
        (list 'user-print display)
        (list 'get-global-environment get-global-environment)
        (list 'define-variable! define-variable!)
        (list 'if-predicate if-predicate)
        (list 'if-alternative if-alternative)
        (list 'if-consequent if-consequent)
        (list 'set-variable-value! set-variable-value!)
        (list 'true? true?)
        (list 'lambda? lambda?)
        (list 'begin? begin?)
        (list 'application? application?)
        (list 'lookup-variable-value lookup-variable-value)
        (list 'lambda-parameters lambda-parameters)
        (list 'lambda-body lambda-body)
        (list 'make-procedure make-procedure)
        (list 'operands operands)
        (list 'operator operator)
        (list 'no-operands? no-operands?)
        (list 'adjoin-arg adjoin-arg)
        (list 'first-operand first-operand)
        (list 'rest-operands cdr)
        (list 'last-operand? last-operand?)
        (list 'procedure-body procedure-body)
        (list 'primitive-procedure? primitive-procedure?)
        (list 'compound-procedure? compound-procedure?)
        (list 'apply-primitive-procedure apply-primitive-procedure)
        (list 'procedure-parameters procedure-parameters)
        (list 'procedure-environment procedure-environment)
        (list 'extend-environment extend-environment)
        (list 'begin-actions begin-actions)
        (list 'first-exp first-exp)
        (list 'last-exp? last-exp?)
        (list 'rest-exps rest-exps)
        (list 'prompt-for-input prompt-for-input)
        (list 'empty-arglist '())))